# Generated by Django 4.1.3 on 2023-04-26 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_alter_category_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="catalog",
        ),
        migrations.AddField(
            model_name="item",
            name="owner",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Catalog",
        ),
    ]
