# Generated by Django 4.1.3 on 2023-05-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0004_remove_category_catalog_item_owner_delete_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(default=1, upload_to="images/"),
            preserve_default=False,
        ),
    ]
