# Generated by Django 4.1.3 on 2023-05-16 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0009_rename_owner_cart_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="products",
            new_name="items",
        ),
    ]
